Feature/internet screen
DariaMisaky/HungryWolfes pull request #9
Opened 2021-08-26 09:49 UTC by DariaMisaky

Add internet Screen

2021-08-26 10:07 UTC, mgabbi commented on app/src/main/java/com/example/hungrywolfes/ui/MainActivity.kt
> +@file:Suppress("DEPRECATION")
🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔

2021-08-26 10:17 UTC, mgabbi requested changes

2021-08-26 10:17 UTC, mgabbi commented on app/src/main/java/com/example/hungrywolfes/ui/favoritesScreen/FavoriteFragment.kt
> +            viewModel.favoriteMealList.value?.let { it -> favoriteAdapter.setDataImages(it) }
You don't have to specifically name `it` as it's the default parameter name

2021-08-26 10:39 UTC, cristiwd requested changes

2021-08-26 10:39 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfes/ui/detailsScreen/DetailsViewModel.kt
> +        if (itemInFavorite() == true) {
No need to add == true since itemInFavorite() is returning a NonNullable value.

2021-08-27 05:57 UTC, cristiwd approved these changes

2021-08-27 08:50 UTC, mgabbi approved these changes

2021-08-27 08:54 UTC, merged